# -*- coding: utf-8 -*-
"""mlb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zysYyWcuZWwkpcKbZPi5NDDXRo5rR0iP
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt

d = {'name': [], 'position': []}
r = requests.get('https://www.mlb.com/stats/hits')
soup = BeautifulSoup(r.content, 'html.parser')
table = soup.find(class_="table-scroller-GsCM0EhI scroller")
columns = [c.get_text() for c in table.find_all('abbr')][2::2]
for i in range (len(columns)):
    d[columns[i]] = []

for i in range (1, 31):
  r = requests.get('https://www.mlb.com/stats/hits/?page=' + str(i))
  print('https://www.mlb.com/stats/hits/?page=' + str(i))

  soup = BeautifulSoup(r.content, 'html.parser')
  table = soup.find(class_="table-scroller-GsCM0EhI scroller")

  columns = [c.get_text() for c in table.find_all('abbr')][2::2]
  name = [r.get_text() for r in table.find_all('span', class_="short-IiSPVSQp")]
  position = [r.get_text() for r in table.find_all('div', class_="position-SAxuJGcx")]
  stat = [r.get_text() for r in table.find_all('td')]

  d['name'] += name
  d['position'] += position
  for i in range (len(columns)):
    if i > 12:
      d[columns[i]] += [float(stat[j]) for j in range(i, len(stat),len(columns))]
    elif i > 0:
      d[columns[i]] += [int(stat[j]) for j in range(i, len(stat),len(columns))]
    else:
      d[columns[i]] += [stat[j] for j in range(i, len(stat),len(columns))]

df = pd.DataFrame(d)
df

df.to_csv("players.csv")

df['ISO'] = df['SLG'] - df['AVG']
df['K%'] = df['SO'] / df['AB']
df['BB%'] = df['BB'] / df['AB']

plt.scatter(df['BB%'], df['SB'])

df.groupby('position')['SB'].mean().sort_values().plot(kind='pie')

df.groupby('position')['RBI'].mean().plot(kind='bar')